### ISSUE TITLE
User images download?

### ISSUE THREAD

**Issue by Devicetron** [craftgear/civitai_prompt_scraper#1]
is there a way to download the user images too? a lot of great prompts get lost in the ether because they don't get featured in a model, maybe the prompt scraper can get those.

**Comment by craftgear** [comment]
Do you mean gallery images? 

https://github.com/craftgear/civitai_prompt_scraper/blob/main/_screenshots/gallery.jpeg

**Comment by craftgear** [comment]
close as this is stale.
